# Numpy Learn
Numpy is more powerful than Python List

In [4]:
import numpy as np

print(np.random.rand(2,3))

print(np.array([1,2,3]))

[[0.05864926 0.79626045 0.65767279]
 [0.07895278 0.47045533 0.60000138]]
[1 2 3]


In [6]:
import time

t0=time.time()

L=list(range(100)) # get a list
for _ in range(10000):
    for i in range(len(L)):
        L[i]+=1

t1=time.time()
a=np.array(L)
for _ in range(10000):
    a+=1 # I even don't need for loop to make every element in np + 1

print('time used by list: {:.3f}s'.format(t1-t0))
print('time used by np: {:.3f}'.format(time.time()-t1))

time used by list: 0.059s
time used by np: 0.008


# 1 Numpy Basic
## 1.1 dimension in numpy
1. ndim: return dimension info
2. size: return how much elements in an array
3. concatenate: add array together
4. expand_dims: expand dimension
5. hstack, vstack: stack arrays
6. shape

In [7]:
cars=np.array([5,10,12,6])

print('data: ',cars,'\ndimmension: ',cars.ndim) # ndim return array dimentsion

data:  [ 5 10 12  6] 
dimmension:  1


In [81]:
cars=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print('data: ',cars,'\ndimmension: ',cars.ndim) 

data:  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
dimmension:  2


In [10]:
# add data
cars1=np.array([1,2,3,4])
cars2=np.array([11,22])

cars=np.concatenate([cars1,cars2]) # add to np array together
print(cars)

[ 1  2  3  4 11 22]


In [29]:
# add data to 2 dimension array
test=np.array([1,2,3,4])
print(test)
test1=np.expand_dims(test,0) # expande array dimention horizontal
print(test1)
test2=np.expand_dims(test,1) # expande array dimension vertical
print(test2)

# test_new=[test[-1-i] for i in range(len(test))]
test_new=test[::-1]
print('test new: ',test_new)


test3=test_new[np.newaxis,:]
print(test3)
test4=test_new[:,np.newaxis]
print(test4)

add_test=np.concatenate([test1,test3])
print(add_test)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
test new:  [4 3 2 1]
[[4 3 2 1]]
[[4]
 [3]
 [2]
 [1]]
[[1 2 3 4]
 [4 3 2 1]]


In [31]:
print("add in 1th dimension:\n",np.concatenate([add_test,add_test],axis=0)) # 沿着第一个维度对齐
print("add in 1th dimension:\n",np.concatenate([add_test,add_test],axis=1)) # 沿着第二个维度对齐

add in 1th dimension:
 [[1 2 3 4]
 [4 3 2 1]
 [1 2 3 4]
 [4 3 2 1]]
add in 1th dimension:
 [[1 2 3 4 1 2 3 4]
 [4 3 2 1 4 3 2 1]]


In [33]:
a=np.array([
    [1,2,3],
    [4,5,6]
])

b=np.array([
    [1,2],
    [3,4]
])

c=np.concatenate([a,b],axis=1)
print("a is:\n",a,"\nb is:\n",b,"\nc is:\n",c)

a is:
 [[1 2 3]
 [4 5 6]] 
b is:
 [[1 2]
 [3 4]] 
c is:
 [[1 2 3 1 2]
 [4 5 6 3 4]]


In [34]:
a=np.array([
    [1,2],
    [3,4]
])

b=np.array([
    [5,6],
    [7,8]
])

print('vertical stack:\n',np.vstack([a,b]))
print('horizontal stack:\n',np.hstack([a,b]))

vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [44]:
cars=np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
])

print('dimensions: ',cars.ndim)
print("element size= ",cars.size)
print('first dimension: ',cars.shape[0])
print('second dimension: ',cars.shape[1])
print('third dimension: ',cars.shape[2])


dimensions:  3
element size=  24
first dimension:  2
second dimension:  4
third dimension:  3


## 1.2 select data
1. use index to choose item
2. use slice to choose item
3. a+=1 means add 1 to every item in array
4. np.reshape((3,3))

In [47]:
a=np.array([1,2,3])
print(a)
print(a[0])
print(a[[0,1]]) # choose to items form array a
print(a[[0,0,1,2]])# we can define a list [x,x,x,...] to choos multipul elements from array

[1 2 3]
1
[1 2]
[1 1 2 3]


In [49]:
# slice
print(a[0:2]) # choose [0:2) from array
print(a[1:])  # choose [1:end] from a
print(a[-2:]) # choose from [-2,end] from a


[1 2]
[2 3]
[2 3]


In [52]:
a=np.array(list(range(10)))
print(a)
print(a[::2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [65]:
# multi-dimension array
a=np.array(list(range(1,10)))
print(a)
a=a.reshape((3,3)) # reshape array
print(a)

print('a[:2] is\n',a[:2])
print(a[:2,:2]) 

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
a[:2] is
 [[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [67]:
# select on condition
print(a[a>7])

# every item +1
a=a+1
print(a)

[8 9]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 1.3 basic calculation

In [68]:
# add every item in numpy
L=np.array(list(range(1,10)))
print(L)

L+=3 # every item +3
print(L)

[1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12]


In [76]:
# matrix operation
a=np.array(list(range(1,5))).reshape((2,2))
print(a)

b=np.array(list(range(5,9))).reshape((2,2))
print(b)

print(a.dot(b)) # matrix multiple
print(np.dot(a,b))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [79]:
# Statistical analysis of data
print('max data: ',a.max())
print('min data: ',a.min())
print('sum of data: ',a.sum())

max data:  4
min data:  1
sum of data:  10


In [88]:
print(a)
print('sucession multiply: ',a.prod())
print('size: ',a.size)
print('not zero: ',np.count_nonzero(a))

print('mean value: ',a.mean())
print('medium value: ',np.median(a))

print('standard deviation: ',np.std(a))

[[1 2]
 [3 4]]
sucession multiply:  24
size:  4
not zero:  4
mean value:  2.5
medium value:  2.5
standard deviation:  1.118033988749895


In [90]:
# find index of value
print(a)
print('max value index: ',np.argmax(a))
print('min value index: ',np.argmin(a))

a=np.array([150.1,166.4,183.7,170.8])
print('clip: ',a.clip(160,180))

[[1 2]
 [3 4]]
max value index:  3
min value index:  0
clip:  [160.  166.4 180.  170.8]


## 1.4 change data shape

In [92]:
a=np.array([1,2,3,4,5,6])

print(a)

a_2d=a[np.newaxis,:]
print(a_2d)

a_2d2=np.expand_dims(a,0)
print(a_2d2)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


In [97]:
# ways to change horizontal array to vertical array
a_none=a[:,None]
print(a_none)

a_expand=np.expand_dims(a,axis=1)
print(a_expand)

a_new_axis=a[:,np.newaxis]
print(a_new_axis)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [101]:
print(a_expand)

# Compress array dimensions
a_squeeze=np.squeeze(a_expand)
print(a_squeeze)

a_squeeze_axis=a_expand.squeeze(axis=1)
print(a_squeeze_axis)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [102]:
a = np.array([1,2,3,4,5,6])
a1 = a.reshape([2, 3])
a2 = a.reshape([3,1,2])
print("a1 shape:", a1.shape)
print(a1)
print("a2 shape:", a2.shape)
print(a2)

a1 shape: (2, 3)
[[1 2 3]
 [4 5 6]]
a2 shape: (3, 1, 2)
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [105]:
print(a1)
b=np.transpose(a1) # Matrix transpose
print(b) 

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [106]:
feature_a = np.array([1,2,3,4,5,6])
feature_b = np.array([11,22,33,44,55,66])
c_stack = np.column_stack([feature_a, feature_b])
print(c_stack)

[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]


In [110]:
sample_a = np.array([0, 1.1, 1.11])
sample_b = np.array([1, 2.2, 2.22])
c_stack = np.row_stack([sample_a, sample_b])
print(c_stack)

[[0.   1.1  1.11]
 [1.   2.2  2.22]]


In [111]:
a = np.array(
[[ 1, 11, 2, 22],
 [ 3, 33, 4, 44],
 [ 5, 55, 6, 66],
 [ 7, 77, 8, 88]]
)
print(np.vsplit(a, indices_or_sections=2))  # 分成两段
print(np.vsplit(a, indices_or_sections=[2,3]))  # 分片成 [:2]，[2:3], [3:]

[array([[ 1, 11,  2, 22],
       [ 3, 33,  4, 44]]), array([[ 5, 55,  6, 66],
       [ 7, 77,  8, 88]])]
[array([[ 1, 11,  2, 22],
       [ 3, 33,  4, 44]]), array([[ 5, 55,  6, 66]]), array([[ 7, 77,  8, 88]])]


# 2 Numpy and files
## 2.1 load data and store data

In [21]:
# open data using python file operation
import numpy as np
import os
with open('day_wise.csv','r') as f:
    data=f.read()
#print(data)

In [20]:
# open data using numpy
data=np.loadtxt('day_wise.csv',dtype=str,delimiter=',',skiprows=1)
print(data[1:10]) # show data from row 1 to row 10


[['2020-01-23' '654' '18' '30' '606' '99' '1' '2' '2.75' '4.59' '60.0'
  '8']
 ['2020-01-24' '941' '26' '36' '879' '287' '8' '6' '2.76' '3.83' '72.22'
  '9']
 ['2020-01-25' '1434' '42' '39' '1353' '493' '16' '3' '2.93' '2.72'
  '107.69' '11']
 ['2020-01-26' '2118' '56' '52' '2010' '684' '14' '13' '2.64' '2.46'
  '107.69' '13']
 ['2020-01-27' '2927' '82' '61' '2784' '809' '26' '9' '2.8' '2.08'
  '134.43' '16']
 ['2020-01-28' '5578' '131' '107' '5340' '2651' '49' '46' '2.35' '1.92'
  '122.43' '16']
 ['2020-01-29' '6166' '133' '125' '5908' '588' '2' '18' '2.16' '2.03'
  '106.4' '18']
 ['2020-01-30' '8234' '171' '141' '7922' '2068' '38' '16' '2.08' '1.71'
  '121.28' '20']
 ['2020-01-31' '9927' '213' '219' '9495' '1693' '42' '78' '2.15' '2.21'
  '97.26' '24']]


# 3 Numpy Projects
## 3.1 Epidemic data analysis

In [142]:
# initial data
covid={'data': [[555.0, 17.0, 28.0, 510.0, 0.0, 0.0, 0.0, 3.06, 5.05, 60.71, 6.0], [654.0, 18.0, 30.0, 606.0, 99.0, 1.0, 2.0, 2.75, 4.59, 60.0, 8.0], [941.0, 26.0, 36.0, 879.0, 287.0, 8.0, 6.0, 2.76, 3.83, 72.22, 9.0], [1434.0, 42.0, 39.0, 1353.0, 493.0, 16.0, 3.0, 2.93, 2.72, 107.69, 11.0], [2118.0, 56.0, 52.0, 2010.0, 684.0, 14.0, 13.0, 2.64, 2.46, 107.69, 13.0], [2927.0, 82.0, 61.0, 2784.0, 809.0, 26.0, 9.0, 2.8, 2.08, 134.43, 16.0], [5578.0, 131.0, 107.0, 5340.0, 2651.0, 49.0, 46.0, 2.35, 1.92, 122.43, 16.0], [6166.0, 133.0, 125.0, 5908.0, 588.0, 2.0, 18.0, 2.16, 2.03, 106.4, 18.0], [8234.0, 171.0, 141.0, 7922.0, 2068.0, 38.0, 16.0, 2.08, 1.71, 121.28, 20.0], [9927.0, 213.0, 219.0, 9495.0, 1693.0, 42.0, 78.0, 2.15, 2.21, 97.26, 24.0], [12038.0, 259.0, 281.0, 11498.0, 2111.0, 46.0, 62.0, 2.15, 2.33, 92.17, 25.0], [16787.0, 362.0, 459.0, 15966.0, 4749.0, 103.0, 178.0, 2.16, 2.73, 78.87, 25.0], [19887.0, 426.0, 604.0, 18857.0, 3100.0, 64.0, 145.0, 2.14, 3.04, 70.53, 25.0], [23898.0, 492.0, 821.0, 22585.0, 4011.0, 66.0, 217.0, 2.06, 3.44, 59.93, 26.0], [27643.0, 564.0, 1071.0, 26008.0, 3745.0, 72.0, 250.0, 2.04, 3.87, 52.66, 26.0], [30802.0, 634.0, 1418.0, 28750.0, 3159.0, 70.0, 347.0, 2.06, 4.6, 44.71, 26.0], [34334.0, 719.0, 1903.0, 31712.0, 3532.0, 85.0, 485.0, 2.09, 5.54, 37.78, 26.0], [37068.0, 806.0, 2470.0, 33792.0, 2734.0, 87.0, 567.0, 2.17, 6.66, 32.63, 26.0], [40095.0, 906.0, 3057.0, 36132.0, 3027.0, 100.0, 587.0, 2.26, 7.62, 29.64, 26.0], [42633.0, 1013.0, 3714.0, 37906.0, 2538.0, 107.0, 657.0, 2.38, 8.71, 27.28, 26.0], [44675.0, 1113.0, 4417.0, 39145.0, 2042.0, 100.0, 703.0, 2.49, 9.89, 25.2, 26.0], [46561.0, 1118.0, 4849.0, 40594.0, 1886.0, 5.0, 432.0, 2.4, 10.41, 23.06, 26.0], [60206.0, 1371.0, 5930.0, 52905.0, 13645.0, 253.0, 1081.0, 2.28, 9.85, 23.12, 26.0], [66690.0, 1523.0, 7613.0, 57554.0, 6484.0, 152.0, 1683.0, 2.28, 11.42, 20.01, 27.0], [68765.0, 1666.0, 8902.0, 58197.0, 2075.0, 143.0, 1289.0, 2.42, 12.95, 18.71, 27.0], [70879.0, 1770.0, 10319.0, 58790.0, 2114.0, 104.0, 1417.0, 2.5, 14.56, 17.15, 27.0], [72815.0, 1868.0, 11951.0, 58996.0, 1936.0, 98.0, 1632.0, 2.57, 16.41, 15.63, 27.0], [74609.0, 2008.0, 13693.0, 58908.0, 1794.0, 140.0, 1742.0, 2.69, 18.35, 14.66, 27.0], [75030.0, 2123.0, 15394.0, 57513.0, 421.0, 115.0, 1701.0, 2.83, 20.52, 13.79, 28.0], [75577.0, 2246.0, 17369.0, 55962.0, 547.0, 123.0, 1975.0, 2.97, 22.98, 12.93, 28.0], [76206.0, 2250.0, 17966.0, 55990.0, 629.0, 4.0, 597.0, 2.95, 23.58, 12.52, 30.0], [77967.0, 2457.0, 21849.0, 53661.0, 1761.0, 207.0, 3883.0, 3.15, 28.02, 11.25, 30.0], [78290.0, 2467.0, 22304.0, 53519.0, 323.0, 10.0, 455.0, 3.15, 28.49, 11.06, 31.0], [78854.0, 2627.0, 24047.0, 52180.0, 564.0, 160.0, 1743.0, 3.33, 30.5, 10.92, 36.0], [79707.0, 2707.0, 26652.0, 50348.0, 853.0, 80.0, 2605.0, 3.4, 33.44, 10.16, 41.0], [80670.0, 2767.0, 29077.0, 48826.0, 963.0, 60.0, 2425.0, 3.43, 36.04, 9.52, 47.0], [82034.0, 2810.0, 31919.0, 47305.0, 1364.0, 43.0, 2842.0, 3.43, 38.91, 8.8, 51.0], [83411.0, 2867.0, 35306.0, 45238.0, 1377.0, 57.0, 3387.0, 3.44, 42.33, 8.12, 57.0], [85306.0, 2936.0, 38314.0, 44056.0, 1895.0, 69.0, 3008.0, 3.44, 44.91, 7.66, 61.0], [87690.0, 2990.0, 41208.0, 43492.0, 2384.0, 54.0, 2894.0, 3.41, 46.99, 7.26, 66.0], [89664.0, 3079.0, 44085.0, 42500.0, 1974.0, 89.0, 2877.0, 3.43, 49.17, 6.98, 73.0], [92241.0, 3154.0, 46681.0, 42406.0, 2577.0, 75.0, 2596.0, 3.42, 50.61, 6.76, 76.0], [94540.0, 3249.0, 49619.0, 41672.0, 2299.0, 95.0, 2938.0, 3.44, 52.48, 6.55, 80.0], [97331.0, 3342.0, 52237.0, 41752.0, 2791.0, 93.0, 2618.0, 3.43, 53.67, 6.4, 84.0], [101274.0, 3454.0, 54270.0, 43550.0, 3943.0, 112.0, 2033.0, 3.41, 53.59, 6.36, 93.0], [105312.0, 3553.0, 56760.0, 44999.0, 4038.0, 99.0, 2490.0, 3.37, 53.9, 6.26, 94.0], [109266.0, 3797.0, 59092.0, 46377.0, 3954.0, 244.0, 2332.0, 3.48, 54.08, 6.43, 99.0], [113166.0, 3981.0, 60891.0, 48294.0, 3900.0, 184.0, 1799.0, 3.52, 53.81, 6.54, 102.0], [118190.0, 4260.0, 62802.0, 51128.0, 5024.0, 279.0, 1911.0, 3.6, 53.14, 6.78, 105.0], [125853.0, 4604.0, 65113.0, 56136.0, 7663.0, 344.0, 2311.0, 3.66, 51.74, 7.07, 111.0], [131603.0, 4909.0, 66434.0, 60260.0, 5750.0, 305.0, 1321.0, 3.73, 50.48, 7.39, 113.0], [146008.0, 5406.0, 68359.0, 72243.0, 14405.0, 497.0, 1925.0, 3.7, 46.82, 7.91, 120.0], [157114.0, 5823.0, 70729.0, 80562.0, 11106.0, 417.0, 2370.0, 3.71, 45.02, 8.23, 133.0], [168260.0, 6464.0, 74139.0, 87657.0, 11146.0, 641.0, 3410.0, 3.84, 44.06, 8.72, 137.0], [182919.0, 7144.0, 76192.0, 99583.0, 14659.0, 680.0, 2053.0, 3.91, 41.65, 9.38, 143.0], [198757.0, 7948.0, 78944.0, 111865.0, 15838.0, 804.0, 2752.0, 4.0, 39.72, 10.07, 146.0], [218343.0, 8845.0, 81427.0, 128071.0, 19586.0, 897.0, 2483.0, 4.05, 37.29, 10.86, 150.0], [246261.0, 9951.0, 83064.0, 153246.0, 27918.0, 1106.0, 1637.0, 4.04, 33.73, 11.98, 154.0], [275869.0, 11429.0, 85509.0, 178931.0, 29608.0, 1478.0, 2445.0, 4.14, 31.0, 13.37, 161.0], [308175.0, 13134.0, 89775.0, 205266.0, 32306.0, 1705.0, 4266.0, 4.26, 29.13, 14.63, 163.0], [341585.0, 14831.0, 95990.0, 230764.0, 33410.0, 1697.0, 6215.0, 4.34, 28.1, 15.45, 168.0], [383750.0, 16748.0, 96456.0, 270546.0, 42165.0, 1917.0, 466.0, 4.36, 25.14, 17.36, 169.0], [424889.0, 19016.0, 105997.0, 299876.0, 41154.0, 2268.0, 9541.0, 4.48, 24.95, 17.94, 171.0], [475706.0, 21793.0, 111445.0, 342468.0, 50817.0, 2777.0, 5448.0, 4.58, 23.43, 19.55, 174.0], [538666.0, 24800.0, 119804.0, 394062.0, 62960.0, 3007.0, 8359.0, 4.6, 22.24, 20.7, 175.0], [603066.0, 28318.0, 128508.0, 446240.0, 64400.0, 3518.0, 8704.0, 4.7, 21.31, 22.04, 176.0], [670723.0, 31997.0, 136800.0, 501926.0, 67657.0, 3679.0, 8292.0, 4.77, 20.4, 23.39, 176.0], [730300.0, 35470.0, 146261.0, 548569.0, 59577.0, 3473.0, 9461.0, 4.86, 20.03, 24.25, 176.0], [794939.0, 39634.0, 161707.0, 593598.0, 64639.0, 4164.0, 15446.0, 4.99, 20.34, 24.51, 177.0], [871355.0, 44478.0, 174074.0, 652803.0, 76416.0, 4844.0, 12367.0, 5.1, 19.98, 25.55, 179.0], [947569.0, 50029.0, 189434.0, 708106.0, 76214.0, 5551.0, 15360.0, 5.28, 19.99, 26.41, 179.0], [1028968.0, 56334.0, 206052.0, 766582.0, 81399.0, 6305.0, 16618.0, 5.47, 20.03, 27.34, 180.0], [1112123.0, 62319.0, 221060.0, 828744.0, 83155.0, 5985.0, 15008.0, 5.6, 19.88, 28.19, 180.0], [1192586.0, 68160.0, 241072.0, 883354.0, 80463.0, 5841.0, 20012.0, 5.72, 20.21, 28.27, 180.0], [1264304.0, 73181.0, 254477.0, 936646.0, 71718.0, 5021.0, 13405.0, 5.79, 20.13, 28.76, 182.0], [1336976.0, 79013.0, 270812.0, 987151.0, 72672.0, 5832.0, 16335.0, 5.91, 20.26, 29.18, 183.0], [1413849.0, 86915.0, 293665.0, 1033269.0, 76873.0, 7902.0, 22853.0, 6.15, 20.77, 29.6, 183.0], [1497624.0, 93650.0, 322017.0, 1081957.0, 83775.0, 6735.0, 28352.0, 6.25, 21.5, 29.08, 183.0], [1584249.0, 101279.0, 346349.0, 1136621.0, 86625.0, 7629.0, 24332.0, 6.39, 21.86, 29.24, 183.0], [1671907.0, 108551.0, 367477.0, 1195879.0, 87658.0, 7272.0, 21128.0, 6.49, 21.98, 29.54, 184.0], [1748872.0, 114620.0, 392991.0, 1241261.0, 76965.0, 6069.0, 25514.0, 6.55, 22.47, 29.17, 184.0], [1845653.0, 120351.0, 411864.0, 1313438.0, 96802.0, 5731.0, 18873.0, 6.52, 22.32, 29.22, 184.0], [1915247.0, 126098.0, 438395.0, 1350754.0, 69594.0, 5747.0, 26531.0, 6.58, 22.89, 28.76, 184.0], [1985174.0, 132996.0, 463014.0, 1389164.0, 69927.0, 6898.0, 24619.0, 6.7, 23.32, 28.72, 184.0], [2066003.0, 141308.0, 498925.0, 1425770.0, 80829.0, 8312.0, 35911.0, 6.84, 24.15, 28.32, 184.0], [2162715.0, 148591.0, 529015.0, 1485109.0, 96712.0, 7283.0, 30090.0, 6.87, 24.46, 28.09, 184.0], [2250439.0, 157481.0, 554287.0, 1538671.0, 87724.0, 8890.0, 25272.0, 7.0, 24.63, 28.41, 184.0], [2324396.0, 163952.0, 577789.0, 1582655.0, 73958.0, 6471.0, 23502.0, 7.05, 24.86, 28.38, 184.0], [2404919.0, 168522.0, 608557.0, 1627840.0, 80523.0, 4570.0, 30768.0, 7.01, 25.3, 27.69, 184.0], [2478258.0, 173965.0, 629862.0, 1674431.0, 73339.0, 5443.0, 21305.0, 7.02, 25.42, 27.62, 184.0], [2553508.0, 181122.0, 664043.0, 1708343.0, 75250.0, 7157.0, 34181.0, 7.09, 26.01, 27.28, 184.0], [2630314.0, 187877.0, 693207.0, 1749230.0, 78994.0, 6755.0, 29164.0, 7.14, 26.35, 27.1, 184.0], [2719327.0, 194727.0, 721689.0, 1802911.0, 89013.0, 6850.0, 28482.0, 7.16, 26.54, 26.98, 184.0], [2806267.0, 201401.0, 771329.0, 1833537.0, 96974.0, 6674.0, 49640.0, 7.18, 27.49, 26.11, 184.0], [2891199.0, 206979.0, 798239.0, 1885981.0, 84932.0, 5578.0, 26910.0, 7.16, 27.61, 25.93, 184.0], [2964146.0, 210862.0, 825969.0, 1927315.0, 72948.0, 3883.0, 27730.0, 7.11, 27.87, 25.53, 184.0], [3032850.0, 215511.0, 852382.0, 1964957.0, 68704.0, 4649.0, 26413.0, 7.11, 28.1, 25.28, 184.0], [3108149.0, 221974.0, 884680.0, 2001495.0, 75404.0, 6463.0, 32298.0, 7.14, 28.46, 25.09, 184.0], [3185195.0, 228742.0, 925752.0, 2030701.0, 79558.0, 6768.0, 41072.0, 7.18, 29.06, 24.71, 184.0], [3268876.0, 234704.0, 989616.0, 2044556.0, 83681.0, 5962.0, 63864.0, 7.18, 30.27, 23.72, 186.0], [3355922.0, 239881.0, 1026501.0, 2089540.0, 87046.0, 5177.0, 36885.0, 7.15, 30.59, 23.37, 186.0], [3437608.0, 245206.0, 1066362.0, 2126040.0, 81853.0, 5325.0, 39861.0, 7.13, 31.02, 22.99, 186.0], [3515244.0, 248659.0, 1097577.0, 2169008.0, 77636.0, 3453.0, 31215.0, 7.07, 31.22, 22.66, 186.0], [3591321.0, 252787.0, 1130526.0, 2208008.0, 76078.0, 4128.0, 32949.0, 7.04, 31.48, 22.36, 186.0], [3671310.0, 258658.0, 1166155.0, 2246497.0, 79989.0, 5871.0, 35629.0, 7.05, 31.76, 22.18, 186.0], [3761332.0, 265327.0, 1210894.0, 2285111.0, 90022.0, 6669.0, 44739.0, 7.05, 32.19, 21.91, 186.0], [3850418.0, 270736.0, 1249311.0, 2330371.0, 90669.0, 5409.0, 38417.0, 7.03, 32.45, 21.67, 186.0], [3941935.0, 276304.0, 1284849.0, 2380782.0, 92997.0, 5568.0, 35538.0, 7.01, 32.59, 21.5, 186.0], [4027781.0, 280569.0, 1337367.0, 2409845.0, 85846.0, 4265.0, 52518.0, 6.97, 33.2, 20.98, 186.0], [4104027.0, 284135.0, 1370108.0, 2449784.0, 76255.0, 3566.0, 32741.0, 6.92, 33.38, 20.74, 186.0], [4180268.0, 287608.0, 1416204.0, 2476456.0, 76298.0, 3473.0, 46096.0, 6.88, 33.88, 20.31, 186.0], [4263867.0, 293155.0, 1452191.0, 2518521.0, 83619.0, 5547.0, 35987.0, 6.88, 34.06, 20.19, 186.0], [4348619.0, 298383.0, 1506905.0, 2543331.0, 84917.0, 5228.0, 54714.0, 6.86, 34.65, 19.8, 187.0], [4445724.0, 303651.0, 1545712.0, 2596361.0, 97106.0, 5268.0, 38807.0, 6.83, 34.77, 19.64, 187.0], [4542073.0, 308866.0, 1592880.0, 2640327.0, 96349.0, 5215.0, 47168.0, 6.8, 35.07, 19.39, 187.0], [4637485.0, 313037.0, 1648546.0, 2675902.0, 95412.0, 4171.0, 55666.0, 6.75, 35.55, 18.99, 187.0], [4715994.0, 316366.0, 1688699.0, 2710929.0, 78509.0, 3329.0, 40153.0, 6.71, 35.81, 18.73, 187.0], [4804278.0, 319657.0, 1740909.0, 2743712.0, 88284.0, 3291.0, 52210.0, 6.65, 36.24, 18.36, 187.0], [4900702.0, 324441.0, 1792256.0, 2784005.0, 96633.0, 4784.0, 51347.0, 6.62, 36.57, 18.1, 187.0], [5003730.0, 329326.0, 1850441.0, 2823963.0, 103028.0, 4885.0, 58185.0, 6.58, 36.98, 17.8, 187.0], [5110064.0, 334112.0, 1900768.0, 2875184.0, 106438.0, 4786.0, 50327.0, 6.54, 37.2, 17.58, 187.0], [5216964.0, 339396.0, 2008541.0, 2869027.0, 106900.0, 5284.0, 107773.0, 6.51, 38.5, 16.9, 187.0], [5322253.0, 343385.0, 2062802.0, 2916066.0, 105289.0, 3989.0, 54261.0, 6.45, 38.76, 16.65, 187.0], [5417579.0, 346525.0, 2117555.0, 2953499.0, 95326.0, 3140.0, 54753.0, 6.4, 39.09, 16.36, 187.0], [5504542.0, 347703.0, 2180605.0, 2976234.0, 87335.0, 1178.0, 63050.0, 6.32, 39.61, 15.95, 187.0], [5597064.0, 351906.0, 2235118.0, 3010040.0, 92742.0, 4203.0, 54513.0, 6.29, 39.93, 15.74, 187.0], [5699664.0, 357119.0, 2297613.0, 3044932.0, 102600.0, 5213.0, 62495.0, 6.27, 40.31, 15.54, 187.0], [5818978.0, 361820.0, 2363746.0, 3093412.0, 119314.0, 4701.0, 66133.0, 6.22, 40.62, 15.31, 187.0], [5940145.0, 366562.0, 2440127.0, 3133456.0, 121167.0, 4742.0, 76381.0, 6.17, 41.08, 15.02, 187.0], [6077978.0, 370718.0, 2509981.0, 3197279.0, 137833.0, 4156.0, 69854.0, 6.1, 41.3, 14.77, 187.0], [6185530.0, 373606.0, 2585589.0, 3226335.0, 107552.0, 2888.0, 75608.0, 6.04, 41.8, 14.45, 187.0], [6280725.0, 376674.0, 2639599.0, 3264452.0, 95195.0, 3068.0, 54010.0, 6.0, 42.03, 14.27, 187.0], [6401536.0, 381497.0, 2743083.0, 3276956.0, 121577.0, 4823.0, 103484.0, 5.96, 42.85, 13.91, 187.0], [6520924.0, 387069.0, 2821430.0, 3312425.0, 119389.0, 5572.0, 78347.0, 5.94, 43.27, 13.72, 187.0], [6647861.0, 392218.0, 2890776.0, 3364867.0, 126937.0, 5149.0, 69346.0, 5.9, 43.48, 13.57, 187.0], [6778724.0, 396994.0, 2959037.0, 3422693.0, 130863.0, 4776.0, 68261.0, 5.86, 43.65, 13.42, 187.0], [6914666.0, 400875.0, 3030214.0, 3483577.0, 135942.0, 3881.0, 71177.0, 5.8, 43.82, 13.23, 187.0], [7026925.0, 403617.0, 3084718.0, 3538590.0, 112259.0, 2742.0, 54504.0, 5.74, 43.9, 13.08, 187.0], [7129150.0, 407314.0, 3235640.0, 3486196.0, 102225.0, 3697.0, 150922.0, 5.71, 45.39, 12.59, 187.0], [7253492.0, 412236.0, 3317121.0, 3524135.0, 124342.0, 4922.0, 81481.0, 5.68, 45.73, 12.43, 187.0], [7387517.0, 417441.0, 3395154.0, 3574922.0, 134025.0, 5205.0, 78033.0, 5.65, 45.96, 12.3, 187.0], [7525631.0, 422215.0, 3480121.0, 3623295.0, 138114.0, 4774.0, 84967.0, 5.61, 46.24, 12.13, 187.0], [7654725.0, 426512.0, 3558933.0, 3669280.0, 129094.0, 4297.0, 78812.0, 5.57, 46.49, 11.98, 187.0], [7790735.0, 430750.0, 3644048.0, 3715937.0, 136010.0, 4238.0, 85115.0, 5.53, 46.77, 11.82, 187.0], [7924156.0, 434124.0, 3714006.0, 3776026.0, 133421.0, 3374.0, 69958.0, 5.48, 46.87, 11.69, 187.0], [8043794.0, 437549.0, 3793406.0, 3812839.0, 119638.0, 3425.0, 79400.0, 5.44, 47.16, 11.53, 187.0], [8185197.0, 444416.0, 3890800.0, 3849981.0, 141403.0, 6867.0, 97394.0, 5.43, 47.53, 11.42, 187.0], [8327050.0, 449671.0, 4008201.0, 3869178.0, 141853.0, 5255.0, 117401.0, 5.4, 48.13, 11.22, 187.0], [8466978.0, 454700.0, 4088826.0, 3923452.0, 139928.0, 5029.0, 80625.0, 5.37, 48.29, 11.12, 187.0], [8647784.0, 460973.0, 4183298.0, 4003513.0, 180954.0, 6273.0, 94472.0, 5.33, 48.37, 11.02, 187.0], [8805336.0, 465222.0, 4298603.0, 4041511.0, 157552.0, 4249.0, 115305.0, 5.28, 48.82, 10.82, 187.0], [8933875.0, 469185.0, 4366875.0, 4097815.0, 128539.0, 3963.0, 68272.0, 5.25, 48.88, 10.74, 187.0], [9071733.0, 472756.0, 4458093.0, 4140884.0, 137858.0, 3571.0, 91218.0, 5.21, 49.14, 10.6, 187.0], [9237071.0, 478067.0, 4561696.0, 4197308.0, 165338.0, 5311.0, 103603.0, 5.18, 49.38, 10.48, 187.0], [9408254.0, 483328.0, 4677005.0, 4247921.0, 171183.0, 5261.0, 115309.0, 5.14, 49.71, 10.33, 187.0], [9586141.0, 489955.0, 4769458.0, 4326728.0, 177887.0, 6627.0, 92453.0, 5.11, 49.75, 10.27, 187.0], [9777487.0, 494782.0, 4875774.0, 4406931.0, 191346.0, 4827.0, 106316.0, 5.06, 49.87, 10.15, 187.0], [9955597.0, 499268.0, 4981808.0, 4474521.0, 178110.0, 4486.0, 106034.0, 5.01, 50.04, 10.02, 187.0], [10117227.0, 502357.0, 5070592.0, 4544278.0, 162349.0, 3089.0, 88784.0, 4.97, 50.12, 9.91, 187.0], [10275799.0, 506078.0, 5164494.0, 4605227.0, 158572.0, 3721.0, 93902.0, 4.92, 50.26, 9.8, 187.0], [10449697.0, 511210.0, 5281459.0, 4657028.0, 173898.0, 5132.0, 116965.0, 4.89, 50.54, 9.68, 187.0], [10667386.0, 516221.0, 5397083.0, 4754082.0, 217689.0, 5011.0, 115624.0, 4.84, 50.59, 9.56, 187.0], [10875091.0, 521341.0, 5681477.0, 4672273.0, 207705.0, 5120.0, 284394.0, 4.79, 52.24, 9.18, 187.0], [11078585.0, 526336.0, 5790942.0, 4761307.0, 203495.0, 4995.0, 109465.0, 4.75, 52.27, 9.09, 187.0], [11272152.0, 530705.0, 5986375.0, 4755072.0, 193567.0, 4369.0, 195433.0, 4.71, 53.11, 8.87, 187.0], [11454847.0, 534150.0, 6105546.0, 4815151.0, 182695.0, 3445.0, 119171.0, 4.66, 53.3, 8.75, 187.0], [11622190.0, 537947.0, 6228768.0, 4855475.0, 167343.0, 3797.0, 123222.0, 4.63, 53.59, 8.64, 187.0], [11833034.0, 544054.0, 6373513.0, 4915467.0, 210844.0, 6107.0, 144745.0, 4.6, 53.86, 8.54, 187.0], [12044836.0, 549373.0, 6531016.0, 4964447.0, 211802.0, 5319.0, 157503.0, 4.56, 54.22, 8.41, 187.0], [12273063.0, 554831.0, 6665237.0, 5052995.0, 228227.0, 5458.0, 134221.0, 4.52, 54.31, 8.32, 187.0], [12505640.0, 560142.0, 6804254.0, 5141244.0, 232577.0, 5311.0, 139017.0, 4.48, 54.41, 8.23, 187.0], [12721968.0, 565039.0, 6929711.0, 5227218.0, 216328.0, 4897.0, 125457.0, 4.44, 54.47, 8.15, 187.0], [12914636.0, 568993.0, 7041174.0, 5304469.0, 192668.0, 3954.0, 111463.0, 4.41, 54.52, 8.08, 187.0], [13107415.0, 572808.0, 7181139.0, 5353468.0, 192779.0, 3815.0, 139965.0, 4.37, 54.79, 7.98, 187.0], [13328867.0, 578468.0, 7322897.0, 5427502.0, 221452.0, 5660.0, 141758.0, 4.34, 54.94, 7.9, 187.0], [13559984.0, 583961.0, 7482320.0, 5493703.0, 231122.0, 5493.0, 159423.0, 4.31, 55.18, 7.8, 187.0], [13812525.0, 589760.0, 7634241.0, 5588524.0, 252544.0, 5799.0, 151921.0, 4.27, 55.27, 7.73, 187.0], [14054563.0, 596503.0, 7793760.0, 5664300.0, 242038.0, 6743.0, 159519.0, 4.24, 55.45, 7.65, 187.0], [14292198.0, 602130.0, 7944550.0, 5745518.0, 237635.0, 5627.0, 150790.0, 4.21, 55.59, 7.58, 187.0], [14506845.0, 606159.0, 8032235.0, 5868451.0, 214647.0, 4029.0, 87685.0, 4.18, 55.37, 7.55, 187.0], [14713623.0, 610319.0, 8190777.0, 5912527.0, 206778.0, 4160.0, 158542.0, 4.15, 55.67, 7.45, 187.0], [14947078.0, 616557.0, 8364986.0, 5965535.0, 233565.0, 6238.0, 174209.0, 4.12, 55.96, 7.37, 187.0], [15227725.0, 623540.0, 8541255.0, 6062930.0, 280647.0, 6983.0, 176269.0, 4.09, 56.09, 7.3, 187.0], [15510481.0, 633506.0, 8710969.0, 6166006.0, 282756.0, 9966.0, 169714.0, 4.08, 56.16, 7.27, 187.0], [15791645.0, 639650.0, 8939705.0, 6212290.0, 281164.0, 6144.0, 228736.0, 4.05, 56.61, 7.16, 187.0], [16047190.0, 644517.0, 9158743.0, 6243930.0, 255545.0, 4867.0, 219038.0, 4.02, 57.07, 7.04, 187.0], [16251796.0, 648621.0, 9293464.0, 6309711.0, 204606.0, 4104.0, 134721.0, 3.99, 57.18, 6.98, 187.0], [16480485.0, 654036.0, 9468087.0, 6358362.0, 228693.0, 5415.0, 174623.0, 3.97, 57.45, 6.91, 187.0]], 'date': ['2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09', '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13', '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17', '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21', '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26', '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11', '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15', '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19', '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23', '2020-04-24', '2020-04-25', '2020-04-26', '2020-04-27', '2020-04-28', '2020-04-29', '2020-04-30', '2020-05-01', '2020-05-02', '2020-05-03', '2020-05-04', '2020-05-05', '2020-05-06', '2020-05-07', '2020-05-08', '2020-05-09', '2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13', '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17', '2020-05-18', '2020-05-19', '2020-05-20', '2020-05-21', '2020-05-22', '2020-05-23', '2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27', '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31', '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04', '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12', '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20', '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04', '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16', '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25', '2020-07-26', '2020-07-27'], 'header': ['Confirmed', 'Deaths', 'Recovered', 'Active', 'New cases', 'New deaths', 'New recovered', 'Deaths / 100 Cases', 'Recovered / 100 Cases', 'Deaths / 100 Recovered', 'No. of countries']}

print(covid.keys())

dict_keys(['data', 'date', 'header'])


In [178]:
# print(covid['date']) # 2020-01-22

# get data from 2020-01-22

data=np.array(covid['data'])
header=np.array(covid['header'])
date=np.array(covid['date'])

dic={}
index=np.where(date=='2020-01-22')[0][0] # find index of value

for h,d in zip(header,data[index]):
    dic[h]=d

print(dic)

{'Confirmed': 555.0, 'Deaths': 17.0, 'Recovered': 28.0, 'Active': 510.0, 'New cases': 0.0, 'New deaths': 0.0, 'New recovered': 0.0, 'Deaths / 100 Cases': 3.06, 'Recovered / 100 Cases': 5.05, 'Deaths / 100 Recovered': 60.71, 'No. of countries': 6.0}


In [180]:
# Cumulative diagnosis people
row_index=covid['date'].index("2020-01-24")
column_index=covid['header'].index('Confirmed')
print(row_index,column_index)
cumulative_people=data[row_index,column_index]
print(cumulative_people)


2 0
941.0
<class 'list'>


In [188]:
# 2020 年 7 月 23 日的新增死亡数是多少？
column_index=np.where(header=='New deaths')[0][0]
row_index=np.where(date=='2020-07-23')[0][0]

new_death=data[row_index,column_index]
print(new_death)

9966.0


In [192]:
# 从 1 月 25 日到 7 月 22 日，一共增长了多少确诊病例？
new_case_index=np.where(header=='New cases')[0][0]

row_index1=np.where(date=='2020-01-25')[0][0]
row_index2=np.where(date=='2020-07-22')[0][0]

new_case=data[row_index1+1:row_index2+1,column_index]
print('total new increase: ',new_case.sum())

total new increase:  623498.0


## 3.2 Data cleansing

In [1]:
import numpy as np
row_data = [
["Name", "StudentID", "Age", "AttendClass", "Score"],
["小明", 20131, 10, 1, 67],
["小花", 20132, 11, 1, 88],
["小菜", 20133, None, 1, "98"],
["小七", 20134, 8, 1, 110],
["花菜", 20134, 98, 0, None],
["刘欣", 20136, 12, 0, 12]
]
print(row_data)

[['Name', 'StudentID', 'Age', 'AttendClass', 'Score'], ['小明', 20131, 10, 1, 67], ['小花', 20132, 11, 1, 88], ['小菜', 20133, None, 1, '98'], ['小七', 20134, 8, 1, 110], ['花菜', 20134, 98, 0, None], ['刘欣', 20136, 12, 0, 12]]


In [2]:
data=np.array(row_data)
data # this is a numpy object

array([['Name', 'StudentID', 'Age', 'AttendClass', 'Score'],
       ['小明', 20131, 10, 1, 67],
       ['小花', 20132, 11, 1, 88],
       ['小菜', 20133, None, 1, '98'],
       ['小七', 20134, 8, 1, 110],
       ['花菜', 20134, 98, 0, None],
       ['刘欣', 20136, 12, 0, 12]], dtype=object)

In [3]:
# test numpy object， different numpy array will have different data type
test1=np.array([1,2,3])
test2=np.array([1.1,2.2,3.3])
test3=np.array([1,2,3],dtype=np.float)

print(test1.dtype)
print(test2.dtype)
print(test3.dtype)


int64
float64
float64


/tmp/ipykernel_1776/1397603918.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test3=np.array([1,2,3],dtype=np.float)


In [4]:
data_process = []
for i in range(len(row_data)):
    if i == 0:
        continue    # 不要首行字符串
    # 去掉首列名字
    data_process.append(row_data[i][1:])
data = np.array(data_process, dtype=np.float)
print("data.dtype", data.dtype)
print(data)
print(data.shape)

data.dtype float64
[[2.0131e+04 1.0000e+01 1.0000e+00 6.7000e+01]
 [2.0132e+04 1.1000e+01 1.0000e+00 8.8000e+01]
 [2.0133e+04        nan 1.0000e+00 9.8000e+01]
 [2.0134e+04 8.0000e+00 1.0000e+00 1.1000e+02]
 [2.0134e+04 9.8000e+01 0.0000e+00        nan]
 [2.0136e+04 1.2000e+01 0.0000e+00 1.2000e+01]]
(6, 4)


/tmp/ipykernel_1776/3154759349.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data = np.array(data_process, dtype=np.float)


In [5]:
# data cleanning
sid = data[:, 0]
unique, counts = np.unique(sid, return_counts=True) # get unit data and count
print(sid)
print(unique)     
print(counts)

print(unique[counts>1])
data[4,0]=20135

[20131. 20132. 20133. 20134. 20134. 20136.]
[20131. 20132. 20133. 20134. 20136.]
[1 1 1 2 1]
[20134.]


In [11]:
is_nan=np.isnan(data[:,1])
print("is_nan",is_nan)
nan_idx=np.argwhere(is_nan)
print(nan_idx)
mean_age=data[~np.isnan(data[:,1]),1].mean()
print('mean age: ',mean_age)

is_nan [False False  True False False False]
[[2]]
mean age:  27.8


In [17]:
normal_age_mask=~np.isnan(data[:,1]) & (data[:,1]<20)
print('normal_age_mask: ',normal_age_mask)

print('data:\n',data,'\n')
normal_age_mean=data[normal_age_mask,1].mean()
print('normal_age_mean: ',normal_age_mean)

data[~normal_age_mask,1]=normal_age_mean
print('new data:\n',data)

normal_age_mask:  [ True  True False  True False  True]
data:
 [[2.0131e+04 1.0000e+01 1.0000e+00 6.7000e+01]
 [2.0132e+04 1.1000e+01 1.0000e+00 8.8000e+01]
 [2.0133e+04        nan 1.0000e+00 9.8000e+01]
 [2.0134e+04 8.0000e+00 1.0000e+00 1.1000e+02]
 [2.0135e+04 9.8000e+01 0.0000e+00        nan]
 [2.0136e+04 1.2000e+01 0.0000e+00 1.2000e+01]] 

normal_age_mean:  10.25
new data:
 [[2.0131e+04 1.0000e+01 1.0000e+00 6.7000e+01]
 [2.0132e+04 1.1000e+01 1.0000e+00 8.8000e+01]
 [2.0133e+04 1.0250e+01 1.0000e+00 9.8000e+01]
 [2.0134e+04 8.0000e+00 1.0000e+00 1.1000e+02]
 [2.0135e+04 1.0250e+01 0.0000e+00        nan]
 [2.0136e+04 1.2000e+01 0.0000e+00 1.2000e+01]]


In [19]:
data[data[:,2]==0 ,3]=np.nan

data[:,3]=np.clip(data[:,3],0,100) # Set the upper and lower limits of the score

print('cleaned data:\n',data)

cleaned data:
 [[2.0131e+04 1.0000e+01 1.0000e+00 6.7000e+01]
 [2.0132e+04 1.1000e+01 1.0000e+00 8.8000e+01]
 [2.0133e+04 1.0250e+01 1.0000e+00 9.8000e+01]
 [2.0134e+04 8.0000e+00 1.0000e+00 1.0000e+02]
 [2.0135e+04 1.0250e+01 0.0000e+00        nan]
 [2.0136e+04 1.2000e+01 0.0000e+00        nan]]
