# Numpy Learn
Numpy is more powerful than Python List

In [4]:
import numpy as np

print(np.random.rand(2,3))

print(np.array([1,2,3]))

[[0.05864926 0.79626045 0.65767279]
 [0.07895278 0.47045533 0.60000138]]
[1 2 3]


In [6]:
import time

t0=time.time()

L=list(range(100)) # get a list
for _ in range(10000):
    for i in range(len(L)):
        L[i]+=1

t1=time.time()
a=np.array(L)
for _ in range(10000):
    a+=1 # I even don't need for loop to make every element in np + 1

print('time used by list: {:.3f}s'.format(t1-t0))
print('time used by np: {:.3f}'.format(time.time()-t1))

time used by list: 0.059s
time used by np: 0.008


# 1 Numpy Basic
## 1.1 dimension in numpy
1. ndim: return dimension info
2. size: return how much elements in an array
3. concatenate: add array together
4. expand_dims: expand dimension
5. hstack, vstack: stack arrays

In [7]:
cars=np.array([5,10,12,6])

print('data: ',cars,'\ndimmension: ',cars.ndim) # ndim return array dimentsion

data:  [ 5 10 12  6] 
dimmension:  1


In [8]:
cars=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print('data: ',cars,'\ndimmension: ',cars.ndim) 

data:  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
dimmension:  2


In [10]:
# add data
cars1=np.array([1,2,3,4])
cars2=np.array([11,22])

cars=np.concatenate([cars1,cars2]) # add to np array together
print(cars)

[ 1  2  3  4 11 22]


In [29]:
# add data to 2 dimension array
test=np.array([1,2,3,4])
print(test)
test1=np.expand_dims(test,0) # expande array dimention horizontal
print(test1)
test2=np.expand_dims(test,1) # expande array dimension vertical
print(test2)

# test_new=[test[-1-i] for i in range(len(test))]
test_new=test[::-1]
print('test new: ',test_new)


test3=test_new[np.newaxis,:]
print(test3)
test4=test_new[:,np.newaxis]
print(test4)

add_test=np.concatenate([test1,test3])
print(add_test)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
test new:  [4 3 2 1]
[[4 3 2 1]]
[[4]
 [3]
 [2]
 [1]]
[[1 2 3 4]
 [4 3 2 1]]


In [31]:
print("add in 1th dimension:\n",np.concatenate([add_test,add_test],axis=0)) # 沿着第一个维度对齐
print("add in 1th dimension:\n",np.concatenate([add_test,add_test],axis=1)) # 沿着第二个维度对齐

add in 1th dimension:
 [[1 2 3 4]
 [4 3 2 1]
 [1 2 3 4]
 [4 3 2 1]]
add in 1th dimension:
 [[1 2 3 4 1 2 3 4]
 [4 3 2 1 4 3 2 1]]


In [33]:
a=np.array([
    [1,2,3],
    [4,5,6]
])

b=np.array([
    [1,2],
    [3,4]
])

c=np.concatenate([a,b],axis=1)
print("a is:\n",a,"\nb is:\n",b,"\nc is:\n",c)

a is:
 [[1 2 3]
 [4 5 6]] 
b is:
 [[1 2]
 [3 4]] 
c is:
 [[1 2 3 1 2]
 [4 5 6 3 4]]


In [34]:
a=np.array([
    [1,2],
    [3,4]
])

b=np.array([
    [5,6],
    [7,8]
])

print('vertical stack:\n',np.vstack([a,b]))
print('horizontal stack:\n',np.hstack([a,b]))

vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [41]:
cars=np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
])

print("element size= ",cars.size)
print('first dimension: ',cars.shape[0])
print('second dimension: ',cars.shape[2])

element size=  12
first dimension:  4


IndexError: tuple index out of range