# Numpy Learn
Numpy is more powerful than Python List

In [4]:
import numpy as np

print(np.random.rand(2,3))

print(np.array([1,2,3]))

[[0.05864926 0.79626045 0.65767279]
 [0.07895278 0.47045533 0.60000138]]
[1 2 3]


In [6]:
import time

t0=time.time()

L=list(range(100)) # get a list
for _ in range(10000):
    for i in range(len(L)):
        L[i]+=1

t1=time.time()
a=np.array(L)
for _ in range(10000):
    a+=1 # I even don't need for loop to make every element in np + 1

print('time used by list: {:.3f}s'.format(t1-t0))
print('time used by np: {:.3f}'.format(time.time()-t1))

time used by list: 0.059s
time used by np: 0.008


# 1 Numpy Basic
## 1.1 dimension in numpy
1. ndim: return dimension info
2. size: return how much elements in an array
3. concatenate: add array together
4. expand_dims: expand dimension
5. hstack, vstack: stack arrays
6. shape

In [7]:
cars=np.array([5,10,12,6])

print('data: ',cars,'\ndimmension: ',cars.ndim) # ndim return array dimentsion

data:  [ 5 10 12  6] 
dimmension:  1


In [81]:
cars=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print('data: ',cars,'\ndimmension: ',cars.ndim) 

data:  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
dimmension:  2


In [10]:
# add data
cars1=np.array([1,2,3,4])
cars2=np.array([11,22])

cars=np.concatenate([cars1,cars2]) # add to np array together
print(cars)

[ 1  2  3  4 11 22]


In [29]:
# add data to 2 dimension array
test=np.array([1,2,3,4])
print(test)
test1=np.expand_dims(test,0) # expande array dimention horizontal
print(test1)
test2=np.expand_dims(test,1) # expande array dimension vertical
print(test2)

# test_new=[test[-1-i] for i in range(len(test))]
test_new=test[::-1]
print('test new: ',test_new)


test3=test_new[np.newaxis,:]
print(test3)
test4=test_new[:,np.newaxis]
print(test4)

add_test=np.concatenate([test1,test3])
print(add_test)

[1 2 3 4]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
test new:  [4 3 2 1]
[[4 3 2 1]]
[[4]
 [3]
 [2]
 [1]]
[[1 2 3 4]
 [4 3 2 1]]


In [31]:
print("add in 1th dimension:\n",np.concatenate([add_test,add_test],axis=0)) # 沿着第一个维度对齐
print("add in 1th dimension:\n",np.concatenate([add_test,add_test],axis=1)) # 沿着第二个维度对齐

add in 1th dimension:
 [[1 2 3 4]
 [4 3 2 1]
 [1 2 3 4]
 [4 3 2 1]]
add in 1th dimension:
 [[1 2 3 4 1 2 3 4]
 [4 3 2 1 4 3 2 1]]


In [33]:
a=np.array([
    [1,2,3],
    [4,5,6]
])

b=np.array([
    [1,2],
    [3,4]
])

c=np.concatenate([a,b],axis=1)
print("a is:\n",a,"\nb is:\n",b,"\nc is:\n",c)

a is:
 [[1 2 3]
 [4 5 6]] 
b is:
 [[1 2]
 [3 4]] 
c is:
 [[1 2 3 1 2]
 [4 5 6 3 4]]


In [34]:
a=np.array([
    [1,2],
    [3,4]
])

b=np.array([
    [5,6],
    [7,8]
])

print('vertical stack:\n',np.vstack([a,b]))
print('horizontal stack:\n',np.hstack([a,b]))

vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [44]:
cars=np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]],
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]]
])

print('dimensions: ',cars.ndim)
print("element size= ",cars.size)
print('first dimension: ',cars.shape[0])
print('second dimension: ',cars.shape[1])
print('third dimension: ',cars.shape[2])


dimensions:  3
element size=  24
first dimension:  2
second dimension:  4
third dimension:  3


## 1.2 select data
1. use index to choose item
2. use slice to choose item
3. a+=1 means add 1 to every item in array
4. np.reshape((3,3))

In [47]:
a=np.array([1,2,3])
print(a)
print(a[0])
print(a[[0,1]]) # choose to items form array a
print(a[[0,0,1,2]])# we can define a list [x,x,x,...] to choos multipul elements from array

[1 2 3]
1
[1 2]
[1 1 2 3]


In [49]:
# slice
print(a[0:2]) # choose [0:2) from array
print(a[1:])  # choose [1:end] from a
print(a[-2:]) # choose from [-2,end] from a


[1 2]
[2 3]
[2 3]


In [52]:
a=np.array(list(range(10)))
print(a)
print(a[::2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [65]:
# multi-dimension array
a=np.array(list(range(1,10)))
print(a)
a=a.reshape((3,3)) # reshape array
print(a)

print('a[:2] is\n',a[:2])
print(a[:2,:2]) 

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
a[:2] is
 [[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [67]:
# select on condition
print(a[a>7])

# every item +1
a=a+1
print(a)

[8 9]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 1.3 basic calculation

In [68]:
# add every item in numpy
L=np.array(list(range(1,10)))
print(L)

L+=3 # every item +3
print(L)

[1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12]


In [76]:
# matrix operation
a=np.array(list(range(1,5))).reshape((2,2))
print(a)

b=np.array(list(range(5,9))).reshape((2,2))
print(b)

print(a.dot(b)) # matrix multiple
print(np.dot(a,b))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [79]:
# Statistical analysis of data
print('max data: ',a.max())
print('min data: ',a.min())
print('sum of data: ',a.sum())

max data:  4
min data:  1
sum of data:  10


In [88]:
print(a)
print('sucession multiply: ',a.prod())
print('size: ',a.size)
print('not zero: ',np.count_nonzero(a))

print('mean value: ',a.mean())
print('medium value: ',np.median(a))

print('standard deviation: ',np.std(a))

[[1 2]
 [3 4]]
sucession multiply:  24
size:  4
not zero:  4
mean value:  2.5
medium value:  2.5
standard deviation:  1.118033988749895


In [90]:
# find index of value
print(a)
print('max value index: ',np.argmax(a))
print('min value index: ',np.argmin(a))

a=np.array([150.1,166.4,183.7,170.8])
print('clip: ',a.clip(160,180))

[[1 2]
 [3 4]]
max value index:  3
min value index:  0
clip:  [160.  166.4 180.  170.8]


## 1.4 change data shape

In [92]:
a=np.array([1,2,3,4,5,6])

print(a)

a_2d=a[np.newaxis,:]
print(a_2d)

a_2d2=np.expand_dims(a,0)
print(a_2d2)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


In [97]:
# ways to change horizontal array to vertical array
a_none=a[:,None]
print(a_none)

a_expand=np.expand_dims(a,axis=1)
print(a_expand)

a_new_axis=a[:,np.newaxis]
print(a_new_axis)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [101]:
print(a_expand)

# Compress array dimensions
a_squeeze=np.squeeze(a_expand)
print(a_squeeze)

a_squeeze_axis=a_expand.squeeze(axis=1)
print(a_squeeze_axis)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [102]:
a = np.array([1,2,3,4,5,6])
a1 = a.reshape([2, 3])
a2 = a.reshape([3,1,2])
print("a1 shape:", a1.shape)
print(a1)
print("a2 shape:", a2.shape)
print(a2)

a1 shape: (2, 3)
[[1 2 3]
 [4 5 6]]
a2 shape: (3, 1, 2)
[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [105]:
print(a1)
b=np.transpose(a1) # Matrix transpose
print(b) 

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [106]:
feature_a = np.array([1,2,3,4,5,6])
feature_b = np.array([11,22,33,44,55,66])
c_stack = np.column_stack([feature_a, feature_b])
print(c_stack)

[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]


In [107]:
sample_a = np.array([0, 1.1, 1.11])
sample_b = np.array([1, 2.2,2.22])
c_stack = np.row_stack([sample_a, sample_b])
print(c_stack)

[[0.  1.1]
 [1.  2.2]]
